name: Auto-assign issues to creator

on:
  issues:
    types: [opened]

jobs:
  assign_issue:
    runs-on: ubuntu-latest

    steps:
    - name: Assign the issue to the creator
      uses: actions-ecosystem/action-assign-to-creator@v1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
